{ pkgs, ... }:
{
  # Required by android-studio
  nixpkgs.config.allowUnfree = true;

  # Install android-studio, run and generate SDK
  environment.systemPackages = with pkgs; [
    android-studio
  ];

  # Now you can use emulator generated by Android Studio with nix-ld
  programs.nix-ld = {
    enable = true;
    libraries = (pkgs.steam-run.args.multiPkgs pkgs) ++ (with pkgs; [
      xorg.libxkbfile
    ]);
  }; 
}
